POST /webhook HTTP/1.1
Host: 0.0.0.0:8443
Content-Type: application/json
Content-Length: 654

{
   "update_id":123456789,
   "message":{
      "message_id":123,
      "from":{
         "id":123456789,
         "is_bot":false,
         "first_name":"Test",
         "language_code":"ru-RU"
      },
      "date":1517384207,
      "chat":{
         "id":123456789,
         "type":"private",
         "first_name":"Testr",
         "all_members_are_administrators":false
      },
      "forward_from_message_id":0,
      "text":"Test text",
      "delete_chat_photo":false,
      "group_chat_created":false,
      "supergroup_chat_created":false,
      "channel_chat_created":false,
      "migrate_to_chat_id":0,
      "migrate_from_chat_id":0
   }
}